### ISSUE TITLE
AMP web push broken by service worker messaging

### ISSUE THREAD

**Issue by piscis** [OneSignal/OneSignal-Website-SDK#321]
I'm currently integration `amp-web-push` with OneSignal but have a issue when I subscribe to a site.

After reload the page the service worker throws an exception: 

```
Uncaught (in promise) Error: The controlling service worker does not support amp-web-push.​​​
at sa (cdn.ampproject.org/v0.js:8)
at oa.f.createError (cdn.ampproject.org/v0.js:4)
at cdn.ampproject.org/v0.js:347
at cdn.ampproject.org/v0.js:346
```

This can be observed on your demo site testing with lastest chrome on desktop and mobile: https://onesignal.com/amp-demo.html

**Comment by jasonpang** [comment]
Hi @piscis,

Thank you for reporting this. We've just released a fix for this and it should propagate to all users in a couple days.

**Comment by pun91** [comment]
We still getting this error on our side while reloading same page or when we directly land from google search.

![image 1](https://user-images.githubusercontent.com/40255593/49221247-97462700-f3fe-11e8-90ec-4df8b1ce0094.png)
