### ISSUE TITLE
addListenerForNotificationOpened callback is not getting called which used to work initially

### ISSUE THREAD

**Issue by varunpottigari** [OneSignal/OneSignal-Website-SDK#507]
**Description:**

I am working on an Angular app (Angular 6) and integrated OneSignal push notifications as mentioned in the docs. When the notification is clicked after being displayed on the screen, the "addListenerForNotificationOpened" callback is not getting called. It used to work before (around 2 months back) but stopped working later on.
He is my code in the "index.html" file of the web app. (Tried with the code in "app.component.ts" file as well, but I am facing the same issue).

```
     <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
     <script>

        var OneSignal = window.OneSignal || [];
        OneSignal.push(function () {
            OneSignal.init({
                appId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            });
            console.log('One signal initiated.');
        });

        OneSignal.push(['addListenerForNotificationOpened', function (data) {
            console.log('Notification Clicked');
        }]);

        OneSignal.push(function () {
            OneSignal.on('notificationDisplay', function (event) {
                console.log('Notifiation Displayed');
            });
        });

        OneSignal.push(function () {
            OneSignal.on('notificationDismiss', function (event) {
                console.log('Notification Dismissed');
            });
        });
    </script>
```
Once the page is loaded, OneSignal.init() is called.
When a notification is displayed, "notificationDisplay" event is triggered.
When a notification is dismissed, "notificationDismiss" event is triggered.
But when a notification is clicked, "addListenerForNotificationOpened" function is not called. But the documentation says that it should. (link [here](https://documentation.onesignal.com/docs/web-push-sdk#section--addlistenerfornotificationopened-))

Here is the behavior
![One signal issue](https://user-images.githubusercontent.com/42644609/54811211-26c55d80-4cae-11e9-8383-c0b468e7d051.gif)

**Steps to Reproduce Issue:**

1. Create a basic angular app (Angular version 6 is my version). (I think this is not the issue of Angular, so just an index.html file should do).
2. Add the code to integrate OneSignal push and add the listener as mentioned in the docs (addListenerForNotificationOpened).
3. Create a notification and click it.

**Anything else:**

Can you please look into this and let me know if there is anything else that I have to do.
Thanks in advance.

**Comment by rgomezp** [comment]
Hello,
Thank you for making it very easy to understand the issue you are facing. I think this is somehow related to Angular apps. 

If you've configured OneSignal to switch to the active tab, you probably already have this set in your OneSignal initialization:

```
notificationClickHandlerMatch: 'origin', /* Or maybe you have 'exact' instead of 'origin' */
notificationClickHandlerAction: 'focus',
```

Here's a [GIF using `origin` and `focus`](http://www.giphy.com/gifs/26DN8JtB3TAAeJDVu/fullscreen), and here's a [GIF using `exact` and `focus`](http://www.giphy.com/gifs/l4pTpjyFgPpU0X0S4/fullscreen).

When you're running this test, can you please try calling `OneSignal.log.setLevel('trace');` at the beginning of your code to enable logging, and see if you get output similar to the GIF? What output do you see if it's different?

**Comment by rgomezp** [comment]
https://github.com/OneSignal/OneSignal-Website-SDK/issues/307

**Comment by rgomezp** [comment]
Hello! This issue should be fixed. Please test and confirm. Thank you!

**Comment by varunpottigari** [comment]
Hello,

I have added the logs as well and these are the logs.


(Host) » sendWelcomeNotification: {title: "", message: "Thanks for subscribing!", url: "http://localhost:4200?_osp=do_not_open"}
Message.js:23 Calling display(message, Thanks for subscribing!, 2500).
zone.js:1152 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://onesignal.com/api/v1/notifications with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ zone.js:1152
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
(anonymous) @ zone.js:1147
ZoneAwarePromise @ zone.js:910
global.fetch @ zone.js:1146
call @ OneSignalApiBase.js:47
post @ OneSignalApiBase.js:10
sendNotification @ OneSignalApiShared.js:36
(anonymous) @ EventHelper.js:67
r @ CustomLink.js:163
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
Event.js:64 (Host ⬸ ProxyFrame) » notificationDisplay: {id: "ca7fd505-621b-4ab7-a367-be270c106e74", content: "Thanks for subscribing!", data: {…}, url: "http://localhost:4200?_osp=do_not_open", heading: "OsApp", …}
OneSignalUtils.js:83 Called isPushNotificationsEnabled() .
OneSignalApiBase.js:47 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://onesignal.com/api/v1/notifications/ca7fd505-621b-4ab7-a367-be270c106e74 with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.


As you can see, I am getting the CORS issue as well, but "OneSignalUtils.js:83 Called isPushNotificationsEnabled() ." this is logged upon clicking the notification and no event has been triggered. **I think the issue is not fully resolved.** Can you please look into it once again.

I will be uploading the project shortly on GitHub. 

Thanks!

**Comment by varunpottigari** [comment]
Hello, I have checked it and the issue is not completely resolved. 
I will be updating the project on GitHub shortly as you mentioned. But meanwhile please look into the below logs. 

Called getSubscription() .
Event.js:67 (Host) » notifyButtonSubscribeClick
OneSignalUtils.js:83 Called setSubscription(true) .
OneSignalUtils.js:83 Called checkAndTriggerSubscriptionChanged() .
OneSignalUtils.js:83 Called isPushNotificationsEnabled() .
EventHelper.js:27 The user's subscription state changed from false ⟶ true
Event.js:64 (Host) » subscriptionChange: true
EventHelper.js:66 Sending welcome notification.
Event.js:64 (Host) » sendWelcomeNotification: {title: "", message: "Thanks for subscribing!", url: "http://localhost:4200?_osp=do_not_open"}
Message.js:23 Calling display(message, Thanks for subscribing!, 2500).
Event.js:64 (Host ⬸ ProxyFrame) » notificationDisplay: {id: "cf3bf523-f118-4bb5-9354-482118bd22bd", content: "Thanks for subscribing!", data: {…}, url: "http://localhost:4200?_osp=do_not_open", heading: "OsApp", …}
OneSignalUtils.js:83 Called isPushNotificationsEnabled() .
OneSignalApiBase.js:47 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://onesignal.com/api/v1/notifications/cf3bf523-f118-4bb5-9354-482118bd22bd with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

These are the logs upon clicking on the notification.
OneSignalUtils.js:83 Called isPushNotificationsEnabled() .
OneSignalApiBase.js:47 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://onesignal.com/api/v1/notifications/cf3bf523-f118-4bb5-9354-482118bd22bd with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Thank you

**Comment by rgomezp** [comment]
@varunpottigari ,
Yes. The warning hasn't been resolved. This will not break anything however, so you can ignore it for now.

**Comment by varunpottigari** [comment]
But the callback for "addListenerForNotificationOpened" is still not getting called when the notification is clicked. 

Thank you.

**Comment by rgomezp** [comment]
@varunpottigari ,
Try sending a notification from the dashboard. Welcome notifications and sendSelfNotifications will not trigger the listener.

**Comment by erikramalho** [comment]
Guys for me it stills with problems. Do I have to update any file to get it working?

**Comment by erikramalho** [comment]
@varunpottigari is it working for you? For me it remains the same way... Same behavior you described

**Comment by varunpottigari** [comment]
Hi @rgomezp @erikramalho 
It is working for me when I send a  notification from the dashboard. 
Thank you @rgomezp for the support.

**Comment by erikramalho** [comment]
Hey @rgomezp I'm still getting this message: 

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://onesignal.com/api/v1/notifications/XXXXXXXa with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by rgomezp** [comment]
Hello @erikramalho ,
This was a backend issue so it should no longer be happening. Have you tried sending from the dashboard?

**Comment by erikramalho** [comment]
Hi @rgomezp, thank you very much for you attention to solve this issue.  I just tried again and received the same exact error. I've sent a message from the dashboard with additonal data (key/value) and received the exact same response: 
![Captura de Tela 2019-04-08 às 17 32 59](https://user-images.githubusercontent.com/5274068/55755033-65844300-5a24-11e9-91ba-5c224430a2b4.png)

There is nothing special in my application (Angular 7). If you want, I can send you more details about my environment.

**Comment by erikramalho** [comment]
Hi @rgomezp, thank you very much for you attention to solve this issue.  I just tried again and received the same exact error. I've sent a message from the dashboard with additonal data (key/value) and received the exact same response: 
 ![Captura de Tela 2019-04-08 às 17 32 59](https://user-images.githubusercontent.com/5274068/55755391-420dc800-5a25-11e9-8328-ea1f98025345.png)


There is nothing special in my application (Angular 7). If you want, I can send you more details about my environment.

**Comment by rgomezp** [comment]
@erikramalho ,
This is a warning which means it will not impact your app. You can ignore it.

**Comment by erikramalho** [comment]
Hey Unfortunately, the "addListenerForNotificationOpened" is never fire.  I've tried 
`        OneSignal.on('addListenerForNotificationOpened', (data) => {
            console.log(data)
          })`
and 
`OneSignal.push(['addListenerForNotificationOpened', function (data) {
            console.log(data);
        }]);`

Both never fires. Do you need any other info from me to help me? It's simply doesn't fire. I'm using a regular Angular 7 application... I'll be glad to reach you in any other channel so I can show you.

**Comment by rgomezp** [comment]
Please reach out to support at onesignal.com

**Comment by erikramalho** [comment]
Hi @varunpottigari I just configured like you said: 
![Captura de Tela 2019-04-09 às 10 00 46](https://user-images.githubusercontent.com/5274068/55802586-e9830d00-5aae-11e9-9853-a03caedff221.png)

I put a console.log and an Alert to track the addListenerForNotificationOpened click but nothing happens.

**Comment by iosifpetre18** [comment]
I had the same issue with the addListenerForNotificationOpened event, but because the the url was opened on a new tab, the event was called on that other tab instance :D
